import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: "#000000",
              // Alias Token
              colorBgContainer: "#ffffff",
            },
          }}
        >
          <div className="page">
            <Navbar />
            {children}
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
